[package]
name = "calculator"
version = "0.10.0"
authors = ["Niko Matsakis <niko@alum.mit.edu>"]
build = "build.rs" # <-- We added this and everything after!

[build-dependencies]
lalrpop = "0.10.0"

[dependencies]
lalrpop-util = "0.10.0"
