language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - cd lalrpop
  - cargo test
  - cd ../lalrpop-test
  - cargo test
  - cd ../doc/calculator
  - cargo test
  - cd ../lalrpop-exe
  - cargo build