[package]
name = "lalrpop"
version = "0.1.0"
authors = ["Niko Matsakis <niko@alum.mit.edu>"]

[dependencies]
regex = "0.1"

[dependencies.rusty-peg]
git = "https://github.com/nikomatsakis/rusty-peg.git"