[workspace]
members = [
        "lalrpop",
        "lalrpop-test",
        "lalrpop-snap",
        "lalrpop-intern",
        "lalrpop-util",
        "doc/calculator",
        "doc/pascal/lalrpop",
        "doc/whitespace",
]
