[package]
name = "lalrpop"
version = "0.1.0"
authors = ["Niko Matsakis <niko@alum.mit.edu>"]
build = "build.rs"

[dependencies]
regex = "0.1"
diff = "0.1"
rand = "0.3"
itertools = "0.3"
term = "0.2"
unicode-xid = "0.0.2"

[dependencies.rusty-peg]
git = "https://github.com/nikomatsakis/rusty-peg.git"

[build-dependencies.lalrpop-snap]
path = "../lalrpop-snap"
