[package]
name = "lalrpop"
version = "0.2.0" # LALRPOP
description = "convenient LR(1) parser generator"
repository = "https://github.com/nikomatsakis/lalrpop"
readme = "../README.md"
keywords = ["parser", "generator", "LR", "yacc", "grammar"]
license = "Unlicense"
authors = ["Niko Matsakis <niko@alum.mit.edu>"]
build = "build.rs"

[dependencies]
regex = "0.1"
diff = "0.1"
rand = "0.3"
itertools = "0.3"
term = "0.2"
unicode-xid = "0.0.2"

[dependencies.lalrpop-util]
path = "../lalrpop-util"
version = "0.2.0" # LALRPOP

[dependencies.lalrpop-intern]
path = "../lalrpop-intern"
version = "0.2.0" # LALRPOP

[build-dependencies.lalrpop-snap]
path = "../lalrpop-snap"
version = "0.2.0" # LALRPOP

# Enable codegen units: this is probably not the optimal way to do it,
# but codegen units helps a lot with compiling lrgrammar.rs (I think).

[profile.dev]
codegen-units = 4

[profile.test]
codegen-units = 4