[package]
name = "lalrpop"
version = "0.19.1" # LALRPOP
description = "convenient LR(1) parser generator"
repository = "https://github.com/lalrpop/lalrpop"
readme = "../README.md"
keywords = ["parser", "generator", "LR", "yacc", "grammar"]
categories = ["parsing"]
license = "Apache-2.0/MIT"
authors = ["Niko Matsakis <niko@alum.mit.edu>"]
workspace = ".."

exclude = ["build.rs"]

[lib]
doctest = false

[dependencies.ascii-canvas]
version = "2.0"
default_features = false

[dependencies.atty]
version = "0.2"
default_features = false

[dependencies.bit-set]
version = "0.5"
default_features = false

[dependencies.diff]
version = "0.1.12"
default_features = false

[dependencies.pico-args]
version = "0.3.4"
default_features = false

[dependencies.ena]
version = "0.14"
default_features = false

[dependencies.itertools]
version = "0.9"
default_features = false
features = ["use_std"]

[dependencies.regex]
version = "1"
default_features = false
features = ["std"]

[dependencies.regex-syntax]
version = "0.6"
default_features = false

[dependencies.petgraph]
version = "0.5"
default_features = false

[dependencies.string_cache]
version = "0.8"
default_features = false

[dependencies.term]
version = "0.5"
default_features = false

[dependencies.unicode-xid]
version = "0.2"
default_features = false

[dependencies.tiny-keccak]
version = "2.0.2"
features = ["sha3"]


[dev-dependencies]
rand = "0.7"

[dependencies.lalrpop-util]
path = "../lalrpop-util"
version = "0.19.1" # LALRPOP

[features]
# Feature used when developing LALRPOP. Tells the build script to use an existing lalrpop binary to
# generate LALRPOPs own parser instead of using the saved parser.
test = []

lexer = ["lalrpop-util/lexer"]

[package.metadata.docs.rs]
features = ["lexer"]
