[package]
name = "lalrpop"
version = "0.19.1" # LALRPOP
description = "convenient LR(1) parser generator"
repository = "https://github.com/lalrpop/lalrpop"
readme = "../README.md"
keywords = ["parser", "generator", "LR", "yacc", "grammar"]
categories = ["parsing"]
license = "Apache-2.0/MIT"
authors = ["Niko Matsakis <niko@alum.mit.edu>"]
workspace = ".."

exclude = ["build.rs"]

[lib]
doctest = false

[dependencies]
ascii-canvas = "2.0"
atty = "0.2"
bit-set = "0.5"
diff = "0.1.12"
docopt = "1"
ena = "0.14"
itertools = "0.9"
regex = "1"
regex-syntax = "0.6"
petgraph = "0.5"
serde = "1.0"
serde_derive = "1.0"
string_cache = "0.8"
term = "0.5"
unicode-xid = "0.2"
sha2 = "0.8"

[dev-dependencies]
rand = "0.7"

[dependencies.lalrpop-util]
path = "../lalrpop-util"
version = "0.19.1" # LALRPOP

[features]
# Feature used when developing LALRPOP. Tells the build script to use an existing lalrpop binary to
# generate LALRPOPs own parser instead of using the saved parser.
test = []

lexer = ["lalrpop-util/lexer"]

[package.metadata.docs.rs]
features = ["lexer"]
