[package]
name = "lalrpop-test"
version = "0.10.0" # LALRPOP
authors = ["Niko Matsakis <niko@alum.mit.edu>"]
build = "build.rs"

[dependencies.lalrpop-util]
path = "../lalrpop-util"

[build-dependencies.lalrpop]
path = "../lalrpop"

